import Layout from '@/components/Layout'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Discord Bot List</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>

      </Layout>
    </div>
  )
}
