import Head from 'next/head'
import { useSession } from 'next-auth/client'
import AccessDenied from '@/components/AccessDenied'

export default function MePage() {

    const [session] = useSession()

    if(!session) return <AccessDenied />

    return (
        <div>
            <Head>
                <title>{session.user.name} - Discord Server List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}
