import Head from 'next/head'
import { useSession } from 'next-auth/client'
import AccessDenied from '@/components/AccessDenied'
import Layout from '@/components/Layout'
import ProfileCard from '@/components/Profile/ProfileCard'
import { useUser } from '@/lib/hooks/useUser'

export default function MePage() {

    const [session] = useSession()

    if(!session) return <AccessDenied />

    return (
        <div>
            <Head>
                <title>{session.user.name} - Discord Server List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <ProfileCard user={session.user} />
            </Layout>
        </div>
    )
}